export const localizeRoles = {
  Roles: 'الأدوار',
  'Get Profile': 'عرض الملف الشخصي',
  'Update User': 'تعديل مستخدم',
  'Recet Password': 'إعادة تعيين كلمة المرور المستخدمين',
  'Get User': 'عرض المستخدم',
  'Update Profile': 'تحديث الملف الشخصي',
  'Add User': 'إضافة مستخدم',
  'Add Product': 'إضافة منتج',
  'Orders Production Reporter': 'تقرير انتاج الصنف',
  'Get Product': 'عرض المنتج',
  'Delivery Dates Reporter': 'تقرير تواريخ الإستلام',
  'Orders States Reporter': 'تقرير حالات الفواتير',
  'Delete Product': 'حذف المنتج',
  'Get Orders': 'عرض الفواتير',
  'Update Product': 'تعديل المنتج',
  'Daily Reporter': 'تقرير يومي',
  'Get Products': 'عرض المنتجات',
  'Change Password': 'تغيير كلمة المرور حسابه',
  'Get All Users': 'عرض جميع المستخدمين',
  'Add Factory': 'إضافة مصنع',
  'Get Factory': 'عرض المصنع',
  'Get Factories': 'عرض المصانع',
  'Delete Factory': 'حذف المصنع',
  'Update Factory': 'تعديل المصنع',
  'Factory charts': 'رسوم بيانية المصنع',
  Admin: 'مشرف'
}
