name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          echo "RENDERER_VITE_REACT_APP_API_URL=${{ secrets.RENDERER_VITE_REACT_APP_API_URL }}" >> .env
          echo "RENDERER_VITE_REACT_APP_ENV=production" >> .env
          type .env

      - name: Build app
        run: env $(cat .env | xargs) npm run build:win

      - name: Get version from package.json
        id: get_version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          $files = Get-ChildItem -Path ./dist -Recurse -File
          foreach ($file in $files) {
            Write-Host "Uploading $file"
            gh release upload "https://github.com/Mahfoud-Sa/OMS-UI/releases/edit/${{env.VERSION}}" $file.FullName --clobber
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
